### ISSUE TITLE
Mistype in Include

### ISSUE THREAD

**Issue by nbulischeck** [exellian/solid-core#1]
https://github.com/exellian/solid-core/blob/ef8fb332a9957b85e4864136760019e230d3c407/include/platform_dependent.h#L6

**Comment by exellian** [comment]
thanks, but i hope you dont use this libary because its not tested and probably not working :)

**Comment by nbulischeck** [comment]
I don't but I had thought about making a similar one a while back so I figured I'd see where you had gotten along with it!
